### ISSUE TITLE
redirect URI

### ISSUE THREAD

**Issue by TaridaGeorge** [gdgbhu/gmail-php-starter#1]
I can't get it work. The redirect URI ... is wrong I think, or .. it is not as supposed to be. I edited /etc/hosts and insered a line like MY_IP_ADDRESS example.com dev.example.com. After I press the sing in button a page appears and said that MY_APP_NAME would like to "View and manage your mail". I press accept and then the browser redirects to dev.example.com but ... dev.example.com doesn't exist. What should I do ?﻿

**Comment by muffycompo** [comment]
Hello George, have you created a project using the Google developer
console. There you will be able to add your domain (dev.example.com in this
example) as your redirect URI and a callback script that will handle the
authorization code sent back from the OAuth process from Google. You could
send me the script you are trying to use so that I can help put a "second
eye" :)

**Comment by TaridaGeorge** [comment]
I'm using the demo.php and gmail.php from this repo. No other changes. The problem is with my VPS where I have the site hosted. My VPS doesn't have a public domain. The redirection doesn't work because www.dev.example.com. doesn't point where it should.(gmail.php).

**Comment by gdgbhu** [comment]
Are you using a publicly accessible machine for your development? If so,
you will need some way to access resources (webserver) on your machine
using DNS or cheating with your hosts file and registering that endpoint in
Google Developer Console as your Redirect URI. Hope this helps?

**Comment by TaridaGeorge** [comment]
Yup. I think that will work. Thanks for you support !
